--
-- PostgreSQL database dump
--

-- Dumped from database version 12.4
-- Dumped by pg_dump version 12.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: actor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.actor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.actor_id_seq OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: actors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actors (
    id integer DEFAULT nextval('public.actor_id_seq'::regclass) NOT NULL,
    name text,
    age integer,
    gender text
);


ALTER TABLE public.actors OWNER TO postgres;

--
-- Name: castdetails; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.castdetails (
    id integer NOT NULL,
    movie_id integer,
    actor_id integer
);


ALTER TABLE public.castdetails OWNER TO postgres;

--
-- Name: castdetails_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.castdetails_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.castdetails_id_seq OWNER TO postgres;

--
-- Name: castdetails_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.castdetails_id_seq OWNED BY public.castdetails.id;


--
-- Name: movie_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.movie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.movie_id_seq OWNER TO postgres;

--
-- Name: movies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movies (
    id integer DEFAULT nextval('public.movie_id_seq'::regclass) NOT NULL,
    title text,
    releasedate text
);


ALTER TABLE public.movies OWNER TO postgres;

--
-- Name: castdetails id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.castdetails ALTER COLUMN id SET DEFAULT nextval('public.castdetails_id_seq'::regclass);


--
-- Data for Name: actors; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.actors (id, name, age, gender) FROM stdin;
3	Alexandria	45	female
4	Alexandr	45	male
2	Victoria	40	female
5	Bryan	20	male
6	Bryan	20	male
7	Bryan	20	male
1	Mike	85	male
\.


--
-- Data for Name: castdetails; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.castdetails (id, movie_id, actor_id) FROM stdin;
\.


--
-- Data for Name: movies; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.movies (id, title, releasedate) FROM stdin;
3	Hercules	2020-10-15 00:12:13
2	Dumbo	2035-10-10 00:12:12
4	Titanic	2020-10-10 00:12:12
5	Titanic	2020-10-10 00:12:12
6	Titanic	2020-10-10 00:12:12
1	The Lion King	1995-10-10 10:10:10
\.


--
-- Name: actor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.actor_id_seq', 7, true);


--
-- Name: castdetails_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.castdetails_id_seq', 1, false);


--
-- Name: movie_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.movie_id_seq', 6, true);


--
-- Name: actors actors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actors
    ADD CONSTRAINT actors_pkey PRIMARY KEY (id);


--
-- Name: castdetails castdetails_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.castdetails
    ADD CONSTRAINT castdetails_pkey PRIMARY KEY (id);


--
-- Name: movies movies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_pkey PRIMARY KEY (id);


--
-- Name: castdetails castdetails_actor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.castdetails
    ADD CONSTRAINT castdetails_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.actors(id);


--
-- Name: castdetails castdetails_movie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.castdetails
    ADD CONSTRAINT castdetails_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public.movies(id);


--
-- PostgreSQL database dump complete
--

